### ISSUE TITLE
All assets are served as `Content-Type: text/plain`

### ISSUE THREAD

**Issue by zdila** [nguyenbatranvan/vite-multiple-assets#1]
All assets are served as `Content-Type: text/plain`.

**Comment by nguyenbatranvan** [comment]
> All assets are served as `Content-Type: text/plain`.

what is your problem? Can add detailed description about it

**Comment by nguyenbatranvan** [comment]
> In my case the problem is that svg files are served with `Content-Type: text/plain` and browser then won't display it as image.

I have just released a version that supports dynamic **content-type**.This is version `1.1.0`. I will close this issue here
