### ISSUE TITLE
Request return 404 in version 1.2.7

### ISSUE THREAD

**Issue by ZXZhuang** [nguyenbatranvan/vite-multiple-assets#10]
Environment:
Windows 11;  Vite 4.5.1; no SSR

Request return 404 in v1.2.7
![image](https://github.com/nguyenbatranvan/vite-multiple-assets/assets/43693464/1ce54619-c00b-40c2-afaa-71e2d18117a1)
![image](https://github.com/nguyenbatranvan/vite-multiple-assets/assets/43693464/f2294b38-f524-40eb-958d-1f6f506e6b57)
pipe EventListener did not callback

**Comment by nguyenbatranvan** [comment]
> Environment: Windows 11; Vite 4.5.1; no SSR
> 
> Request return 404 in v1.2.7 ![image](https://private-user-images.githubusercontent.com/43693464/290086161-1ce54619-c00b-40c2-afaa-71e2d18117a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDY5MDUsIm5iZiI6MTcwMjQ0NjYwNSwicGF0aCI6Ii80MzY5MzQ2NC8yOTAwODYxNjEtMWNlNTQ2MTktYzAwYi00MGMyLWFmYWEtNzFlMmQxODExN2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA1NTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZlYjcyZGRmMTQ3ZjM4ZGNiMWU0NWI4M2E4ZWZkMGM5M2QwYjQyNjgwOGI4YThhNDQ2NzBlMTg4NWU5ZGY0OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tZpxkY2biBLQV8-19MGytrDNxp3lv_PVbcu4ZSFDANs) ![image](https://private-user-images.githubusercontent.com/43693464/290085973-f2294b38-f524-40eb-958d-1f6f506e6b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NDY5MDUsIm5iZiI6MTcwMjQ0NjYwNSwicGF0aCI6Ii80MzY5MzQ2NC8yOTAwODU5NzMtZjIyOTRiMzgtZjUyNC00MGViLTk1OGQtMWY2ZjUwNmU2YjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA1NTAwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZWRmZGU0NjUwMzZjNzMwNDg3MGU2OTM5NTljNmFhMmI5OTViZjY5NzVlOWYzM2Y3NmVmNjZjNDQ2YzUwODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WJzyv72mRHBdUOL_xZor3xxpTv_jiX-TSlgOm7OH_v8) pipe EventListener did not callback

yess!! i seen! For now you can use a version prior to `1.2.7` while I resolve this issue

**Comment by nguyenbatranvan** [comment]
> Environment: Windows 11; Vite 4.5.1; no SSR
> 
> Request return 404 in v1.2.7 ![image](https://private-user-images.githubusercontent.com/43693464/290086161-1ce54619-c00b-40c2-afaa-71e2d18117a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTgwMTgsIm5iZiI6MTcwMjUxNzcxOCwicGF0aCI6Ii80MzY5MzQ2NC8yOTAwODYxNjEtMWNlNTQ2MTktYzAwYi00MGMyLWFmYWEtNzFlMmQxODExN2ExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAxMzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjZDQyMmM5MGIxZjYzNTNkMDhhYzdkMjMyNTU3MzQ2NTg4ZGM1NmRiZjllZGE3YWZjYzNjYzQ3NDVkM2VkNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uIBPJqUXgDkYhGgqv5T3wwWp6eUb3OMo4H4yZQKuX5c) ![image](https://private-user-images.githubusercontent.com/43693464/290085973-f2294b38-f524-40eb-958d-1f6f506e6b57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MTgwMTgsIm5iZiI6MTcwMjUxNzcxOCwicGF0aCI6Ii80MzY5MzQ2NC8yOTAwODU5NzMtZjIyOTRiMzgtZjUyNC00MGViLTk1OGQtMWY2ZjUwNmU2YjU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE0VDAxMzUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MTFhNzRjZTAxYjgwNTAxYjFiMzVjZDI1MzdkYmJhY2NhZGRmYmEyMjBhYTgyNjY0MDNiNDU3NWJiYWU4ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dW1H_dOtFadI4Q9cRK0ChrcvHebBHbSsTSO0mvPtxpU) pipe EventListener did not callback

i released version `1.2.8`. Please check again and there are some changes, please read readme.md for updates

**Comment by ZXZhuang** [comment]
v1.2.8 is ok
