### ISSUE TITLE
Clarify the license for the project

### ISSUE THREAD

**Issue by maxpatiiuk** [nguyenbatranvan/vite-multiple-assets#15]
Could you please create a `LICENSE` file in this repository to make it clear what are the usage restrictions and permissions for this project and what is your policy for forks?
Thank you
(i.e a MIT licence: https://github.com/git/git-scm.com/blob/main/MIT-LICENSE.txt)

**Comment by Keavon** [comment]
MIT would be appreciated as it's most appropriate for simple single-purpose tooling like this.

**Comment by nguyenbatranvan** [comment]
now i have added it
