### ISSUE TITLE
Not working in Astro dev mode (works fine during build)

### ISSUE THREAD

**Issue by heyitsdoodler** [nguyenbatranvan/vite-multiple-assets#19]
I have an Astro project and this package works perfectly for shared assets when building the project but doesn't work in dev mode.

Would you possibly know how to fix this?

**Comment by nguyenbatranvan** [comment]
> I have an Astro project and this package works perfectly for shared assets when building the project but doesn't work in dev mode.
> 
> Would you possibly know how to fix this?

do you have a repo on this? it would be great if you share it

**Comment by heyitsdoodler** [comment]
Hi, thanks for responding.

Here's a [demo repository](https://github.com/heyitsdoodler/astro-multi-file-demo).

**Comment by nguyenbatranvan** [comment]
> Hi, thanks for responding.
> 
> Here's a [demo repository](https://github.com/heyitsdoodler/astro-multi-file-demo).

I will work tomorrow!! Thanks for your feedback

**Comment by nguyenbatranvan** [comment]
> > Hi, thanks for responding.
> > Here's a [demo repository](https://github.com/heyitsdoodler/astro-multi-file-demo).
> 
> I will work tomorrow!! Thanks for your feedback

Hello!! Version `1.3.0` published! Check example from [Astro example](https://github.com/nguyenbatranvan/vite-multiple-assets/blob/main/packages/examples/astro/astro.config.mjs)

**Comment by heyitsdoodler** [comment]
> > > Hi, thanks for responding.
> > > Here's a [demo repository](https://github.com/heyitsdoodler/astro-multi-file-demo).
> > 
> > 
> > I will work tomorrow!! Thanks for your feedback
> 
> Hello!! Version `1.3.0` published! Check example from [Astro example](https://github.com/nguyenbatranvan/vite-multiple-assets/blob/main/packages/examples/astro/astro.config.mjs) Because astro will not directly listen to serve middleware from vite, there will be a function exported and passed serve from astro into

That was fast, thanks so much :)
