### ISSUE TITLE
Feature: Custom Path for Asset Path

### ISSUE THREAD

**Issue by shellscape** [nguyenbatranvan/vite-multiple-assets#22]
First off, thank you for this plugin. We're going to use it in jsx.email and it's going to make a lot of people very happy. 

I was wondering if there was a way that this plugin could enable custom url paths from the root that would correspond to an asset directory. e.g.

```ts
DynamicPublicDirectory({
    assets: join(targetPath, '**')
  },
  { ssr: false }
);
```

Which could then be accessed in the browser as such: `<img src="/assets/file.png" />`

The obvious solution is to tell the user to create a subdirectory in the target assets directory, but I was curious if this kind of a setup was an option for the plugin.

**Comment by nguyenbatranvan** [comment]
> First off, thank you for this plugin. We're going to use it in jsx.email and it's going to make a lot of people very happy.
> 
> I was wondering if there was a way that this plugin could enable custom url paths from the root that would correspond to an asset directory. e.g.
> 
> ```ts
> DynamicPublicDirectory({
>     assets: join(targetPath, '**')
>   },
>   { ssr: false }
> );
> ```
> 
> Which could then be accessed in the browser as such: `<img src="/assets/file.png" />`
> 
> The obvious solution is to tell the user to create a subdirectory in the target assets directory, but I was curious if this kind of a setup was an option for the plugin.

I don't understand the problem why create subfolder in the  target assets directory? U can [read](https://nguyenbatranvan.github.io/vite-multiple-assets-doc/guide/migration_v2.html),  just add `\x01` before the folder you want to use and it will take from that folder. Ex:
`libs/{\x01,assets}/**` (helps me copy the entire assets folder and the files inside it)

- Use can read the [opts](https://nguyenbatranvan.github.io/vite-multiple-assets-doc/guide/index.html#assets)

Is this what you want?

**Comment by shellscape** [comment]
jsx.email is using vite in a very specialized and non-typical way. it would desirable for people to use something like `/template-assets/` to create a contract for all users, rather than the root.

**Comment by nguyenbatranvan** [comment]
> jsx.email is using vite in a very specialized and non-typical way. it would desirable for people to use something like `/template-assets/` to create a contract for all users, rather than the root.

Do you mean monorepo and 1 app at a different level than root?

**Comment by nguyenbatranvan** [comment]
I'm not sure what you want? And is it like in this [example](https://github.com/nguyenbatranvan/vite-multiple-assets/blob/main/packages/examples/react/vite.config.ts)?

**Comment by intelligentRaji** [comment]
@nguyenbatranvan It would be cool if there will be a way to create a cutom path for the spific folder.

Now, I'm creating an Angular SSR application with help of [Analogjs](https://analogjs.org/) angular meta-framework. The framework uses Vite as a builder. And I have a problem, because besides the framework, I'm using [TaigaUI](https://taiga-ui.dev/) library. That library provides an `icon-component`, and under the hood the component search for icons in the specific folder by path `'/assets/taiga-ui/icons'`.

And here is the problem. Because according to `TaigaUI` docs part of library settup is adding this block of code in `angular.json` configuration

```json
"assets": [
              {
                "glob": "**/*",
                "input": "node_modules/@taiga-ui/icons/src",
                "output": "/assets/taiga-ui/icons"
              }
            ]
```
What it means? It means what every file matching the pattern `glob` form folder `node_modules/@taiga-ui/icons/src` will be static in the folder `/assets/taiga-ui/icons`. But vite does not provide such control over static folders.

[Angular assets configuration documentation](https://angular.dev/reference/configs/workspace-config#assets-configuration)

Thank you!

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan It would be cool if there will be a way to create a cutom path for the spific folder.
> 
> Now, I'm creating an Angular SSR application with help of [Analogjs](https://analogjs.org/) angular meta-framework. The framework uses Vite as a builder. And I have a problem, because besides the framework, I'm using [TaigaUI](https://taiga-ui.dev/) library. That library provides an `icon-component`, and under the hood the component search for icons in the specific folder by path `'/assets/taiga-ui/icons'`.
> 
> And here is the problem. Because according to `TaigaUI` docs part of library settup is adding this block of code in `angular.json` configuration
> 
> ```json
> "assets": [
>               {
>                 "glob": "**/*",
>                 "input": "node_modules/@taiga-ui/icons/src",
>                 "output": "/assets/taiga-ui/icons"
>               }
>             ]
> ```
> 
> What it means? It means what every file matching the pattern `glob` form folder `node_modules/@taiga-ui/icons/src` will be static in the folder `/assets/taiga-ui/icons`. But vite does not provide such control over static folders.
> 
> [Angular assets configuration documentation](https://angular.dev/reference/configs/workspace-config#assets-configuration)
> 
> It would be cool if you add functionality what provides same control or better control over static folders what angular provides.
> 
> Thank you! 😊

it would be great if there was a repo of your config

**Comment by nguyenbatranvan** [comment]
sorry, as I understand you guys need custom output support with root directory?

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan It would be cool if there will be a way to create a cutom path for the spific folder.
> 
> Now, I'm creating an Angular SSR application with help of [Analogjs](https://analogjs.org/) angular meta-framework. The framework uses Vite as a builder. And I have a problem, because besides the framework, I'm using [TaigaUI](https://taiga-ui.dev/) library. That library provides an `icon-component`, and under the hood the component search for icons in the specific folder by path `'/assets/taiga-ui/icons'`.
> 
> And here is the problem. Because according to `TaigaUI` docs part of library settup is adding this block of code in `angular.json` configuration
> 
> ```json
> "assets": [
>               {
>                 "glob": "**/*",
>                 "input": "node_modules/@taiga-ui/icons/src",
>                 "output": "/assets/taiga-ui/icons"
>               }
>             ]
> ```
> 
> What it means? It means what every file matching the pattern `glob` form folder `node_modules/@taiga-ui/icons/src` will be static in the folder `/assets/taiga-ui/icons`. But vite does not provide such control over static folders.
> 
> [Angular assets configuration documentation](https://angular.dev/reference/configs/workspace-config#assets-configuration)
> 
> It would be cool if you add functionality what provides same control or better control over static folders what angular provides.
> 
> Thank you! 😊

My library doesn't support this yet, but you can temporarily use the config and use it as a parent. Maybe I'll add these features soon. Thanks!!

```
DynamicPublicDirectory(["node_modules/@taiga-ui/icons/src/**"], {
            ssr: true, // if serve side rendering
 }) as PluginOption
        
```

**Comment by nguyenbatranvan** [comment]
i released `v2.1.1` support for output path. [View example](https://github.com/nguyenbatranvan/vite-multiple-assets/blob/main/packages/examples/react/vite.config.ts)

@intelligentRaji you can config:

```
 DynamicPublicDirectory([{
            input: "node_modules/@taiga-ui/icons/src/**",
            output: "/assets/taiga-ui/icons"
        }], {
            ssr: true,
   })
        
```

**Comment by FarhanMS123** [comment]
> ```json
> "assets": [
>               {
>                 "glob": "**/*",
>                 "input": "node_modules/@taiga-ui/icons/src",
>                 "output": "/assets/taiga-ui/icons"
>               }
>             ]
> ```
> 
> What it means? It means what every file matching the pattern `glob` form folder `node_modules/@taiga-ui/icons/src` will be static in the folder `/assets/taiga-ui/icons`. But vite does not provide such control over static folders.

This may be opinioned. I just think this is not efficient because this glob designed to take your `input` from `cwd` from options and its designed to run once. I would reccomend if you have multiple cwd, you could recall the plugin with different `cwd`. And also from your root project `process.cwd()`, you could actually do `../node_modules/@taiga-ui/icons/src/**` and change the `dst`.

But actually your idea of `output`, I've made a rough design by this type definition, but never been implemented due time:

```ts
import path from "path/posix";

export interface IConfigExtend extends Partial<Pick<Options, "ignore" | "dot">> {
    dst?: string | FDst;
}
export type IAssets = string[] | string | (IConfigExtend & { assets: string | string[]; })[];

DynamicPublicDirectory([
  "public/**",
  {
    assets: "sample/**.txt",
    ignore: "**photo**"
  },
  {
    assets: ["assets/**", "vars/**"],
    dot: true,
    dst: path.join(__dirname, ".cache")
  },
], {
  dst: ({ dstFile, filepath, }) => filepath.match(/.jpg$/ig) ? false : undefined,
})
```

By fast-glob only run once (for efficiency in I/O cost), after that micromatch could rematch once again by iterating the `assets` and also remap the `dst` to put the file.

**Comment by nguyenbatranvan** [comment]
> > ```json
> > "assets": [
> >               {
> >                 "glob": "**/*",
> >                 "input": "node_modules/@taiga-ui/icons/src",
> >                 "output": "/assets/taiga-ui/icons"
> >               }
> >             ]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > What it means? It means what every file matching the pattern `glob` form folder `node_modules/@taiga-ui/icons/src` will be static in the folder `/assets/taiga-ui/icons`. But vite does not provide such control over static folders.
> 
> This may be opinioned. I just think this is not efficient because this glob designed to take your `input` from `cwd` from options and its designed to run once. I would reccomend if you have multiple cwd, you could recall the plugin with different `cwd`. And also from your root project `process.cwd()`, you could actually do `../node_modules/@taiga-ui/icons/src/**` and change the `dst`.
> 
> But actually your idea of `output`, I've made a rough design by this type definition, but never been implemented due time:
> 
> ```ts
> import path from "path/posix";
> 
> export interface IConfigExtend extends Partial<Pick<Options, "ignore" | "dot">> {
>     dst?: string | FDst;
> }
> export type IAssets = string[] | string | (IConfigExtend & { assets: string | string[]; })[];
> 
> DynamicPublicDirectory([
>   "public/**",
>   {
>     assets: "sample/**.txt",
>     ignore: "**photo**"
>   },
>   {
>     assets: ["assets/**", "vars/**"],
>     dot: true,
>     dst: path.join(__dirname, ".cache")
>   },
> ], {
>   dst: ({ dstFile, filepath, }) => filepath.match(/.jpg$/ig) ? false : undefined,
> })
> ```
> 
> By fast-glob only run once (for efficiency in I/O cost), after that micromatch could rematch once again by iterating the `assets` and also remap the `dst` to put the file.

I have a release on this. Will there be any further tweaking needed?

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Thank you for making such a great plugin! I'm having trouble using monorepo and don't know how to solve it.
```
app
├───📁 apps
│ ├─── 📁shared/
│  |─── 📁 a/
│ └───📁 b
└───📄 vite.config.ts
```
This is the structure of the project. I want to separate the static resources originally written in the shared directory into different folders, so that in the new project, you can freely combine assets without directly copying the huge shared directory.

The base path of the app is `/ts/`. In the `apps/shared/assets/` directory, there is a `static` folder where all static resources are located.

I am using vue3. In the original code, I implemented static resource acquisition in two ways, one was to write '/static/...' directly in css, and the other was as follows:
```ts
// eg
new URL('/static/images/datamap/calendar.svg', import.meta.url).href
```
The path of the generated static resource file is `/ts//static/images/datamap/calendar.svg`.

I want to keep the reference to the static resources in the original shared directory, and move some internal assets to package a or package b, but these resources are still under static when packing, without affecting dev or prod.

Here's my vite configuration, it doesn't work.

```ts
 publicDir: false,
 plugins: [
 // vue plugin
 vue({
 script: {
 propsDestructure: true
 }
 }),
 // vue jsx plugin
 vueJsx(),
 // multiple assets
 DynamicPublicDirectory(
 [
 {
 input: 'apps/shared/assets/**',
 output: ''
 }
 ],
 {
 cwd: process.cwd()
 }
 ),
 ...
```

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan Thank you for making such a great plugin! I'm having trouble using monorepo and don't know how to solve it.
> 
> ```
> app
> ├───📁 apps
> │ ├─── 📁shared/
> │ |─── 📁 a/
> │ └───📁 b
> └───📄 vite.config.ts
> ```
> 
> This is the structure of the project. I want to separate the static resources originally written in the shared directory into different folders, so that in the new project, you can freely combine assets without directly copying the huge shared directory.
> 
> The base path of the app is `/ts/`. In the `apps/shared/assets/` directory, there is a `static` folder where all static resources are located.
> 
> I am using vue3. In the original code, I implemented static resource acquisition in two ways, one was to write '/static/...' directly in css, and the other was as follows:
> 
> ```ts
> // eg
> new URL('/static/images/datamap/calendar.svg', import.meta.url).href
> ```
> 
> The path of the generated static resource file is `/ts//static/images/datamap/calendar.svg`.
> 
> I want to keep the reference to the static resources in the original shared directory, and move some internal assets to package a or package b, but these resources are still under static when packing, without affecting dev or prod.
> 
> Here's my vite configuration, it doesn't work.
> 
> ```ts
>  publicDir: false,
>  plugins: [
>  // vue plugin
>  vue({
>  script: {
>  propsDestructure: true
>  }
>  }),
>  // vue jsx plugin
>  vueJsx(),
>  // multiple assets
>  DynamicPublicDirectory(
>  [
>  {
>  input: 'apps/shared/assets/**',
>  output: ''
>  }
>  ],
>  {
>  cwd: process.cwd()
>  }
>  ),
>  ...
> ```

do you have a small repo for this? i would like to see more details

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Yes, I created a repository for this issue. https://github.com/zhixiaotong/monorepo-assets-demo

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan Yes, I created a repository for this issue. https://github.com/zhixiaotong/monorepo-assets-demo

i'm not sure!! Maybe repo private?

**Comment by zhixiaotong** [comment]
> > @nguyenbatranvan Yes, I created a repository for this issue. https://github.com/zhixiaotong/monorepo-assets-demo
> 
> i'm not sure!! Maybe repo private?

oh…sorry. It can be seen now.

**Comment by nguyenbatranvan** [comment]
> > > @nguyenbatranvan Yes, I created a repository for this issue. https://github.com/zhixiaotong/monorepo-assets-demo
> > 
> > 
> > i'm not sure!! Maybe repo private?
> 
> oh…sorry. It can be seen now.

I looked at your repo this morning, this is not caused by my plugin. It is due to the way you construct the URL incorrectly:

Current: `apps/a/src/TestA.vue` :

```
const picture1 = new URL('/static/images/databases/clickhouse.png', import.meta.url).href
```

Change to:

```
const picture1 = new URL('/static/images/databases/clickhouse.png', new URL('', import.meta.url)).href
```

Similar to other `new URLs`

`vite.config.ts` can be shortened as follows:

```
export default defineConfig({
  // publicDir: 'apps/shared/assets',
  plugins: [
    vue(),
    DynamicPublicDirectory([
         'apps/shared/assets/**'
        // same to  {input: 'apps/shared/assets/**', output:""}
    ])
  ],
})
```

In addition to the above import method, you can refer to my [Vue3 example](https://github.com/nguyenbatranvan/vite-multiple-assets/blob/main/packages/examples/vue3/vite.config.ts).

**Comment by nguyenbatranvan** [comment]
> /static/images/databases/clickhouse.png

It doesn't have to be 2 URLs, as long as the generated path is `http://{domain}/static/images/databases/clickhouse.png`

**Comment by zhixiaotong** [comment]
> > /static/images/databases/clickhouse.png
> 
> It doesn't have to be 2 URLs, as long as the generated path is `http://{domain}/static/images/databases/clickhouse.png`

OK. Thank you again for your help.｡◕‿◕｡

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Good morning, sorry to bother you. I tried it and found that originally only writing one URL was enough. The difference between the two is that one is a function and the other is a directly generated variable. In the dev environment, the generated path contains `@fs`, which may be related to the internal processing of the plugin.

In addition, I added the respective assets references for package `a` and package `b` in the configuration, which cannot be displayed normally in the dev environment, but can be displayed normally after building, and the generated package structure is also normal. Please take a look, thank you very much.

![image](https://github.com/user-attachments/assets/ea7aea67-4d21-4908-be8d-12e5a15b0dc7)

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan Good morning, sorry to bother you. I tried it and found that originally only writing one URL was enough. The difference between the two is that one is a function and the other is a directly generated variable. In the dev environment, the generated path contains `@fs`, which may be related to the internal processing of the plugin.
> 
> In addition, I added the respective assets references for package `a` and package `b` in the configuration, which cannot be displayed normally in the dev environment, but can be displayed normally after building, and the generated package structure is also normal. Please take a look, thank you very much.
> 
> ![image](https://private-user-images.githubusercontent.com/34681550/383379906-ea7aea67-4d21-4908-be8d-12e5a15b0dc7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NTkyNTAsIm5iZiI6MTczMDg1ODk1MCwicGF0aCI6Ii8zNDY4MTU1MC8zODMzNzk5MDYtZWE3YWVhNjctNGQyMS00OTA4LWJlOGQtMTJlNWExNWIwZGM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMDkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmZGM0NGQ3OWU4M2E5ZDQ4M2JjMGU3ZWIxMzBhYTNjNmM1N2Q0ZWNjZjFiMmI2ODUzNjRiZTg2YWMyNTMzZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ohrf-_PxdbJ1kebaDofQATIlHpe0mu1nVZ0JUb2-X5k)

I have created a new issue for your problem, please discuss [here](https://github.com/nguyenbatranvan/vite-multiple-assets/issues/24).
