### ISSUE TITLE
Feature: Follow Symlinks

### ISSUE THREAD

**Issue by shellscape** [nguyenbatranvan/vite-multiple-assets#23]
If I have a plugin setup such as:

```ts
DynamicPublicDirectory([
    '/Users/code/app/assets/**'
  ],
  { ssr: false }
);
```

And I add a symlink to the `/assets` directory for `test.png`, that file is not available in the server and `getFiles` doesn't add it to the list of files available. Following symlinks would solve this, and open up a LOT of possibilities for this plugin.

**Comment by shellscape** [comment]
I added `followSymbolicLinks` on this line https://github.com/nguyenbatranvan/vite-multiple-assets/blob/cee159314911794110a3e242cae61660cdadda47/packages/libs/build.ts#L76 and it allowed me to access the file in the browser. Would be a huge improvement!

**Comment by nguyenbatranvan** [comment]
I'm looking into this!! No sure time for it yet

**Comment by nguyenbatranvan** [comment]
Hi @shellscape !! So far I have supported symlinks with my library. You can simply add `followSymbolicLinks :true` in the options. You can see it [here](https://nguyenbatranvan.github.io/vite-multiple-assets-doc/guide/index.html#optsfollowsymlinks). I saw your `jsx-email`. It's great, I really hope my library will help you somehow! Thanks

**Comment by shellscape** [comment]
Thank you for all the work here! I will be giving this a try soon.

**Comment by nguyenbatranvan** [comment]
Please give me feedback if there is any problem with it!! Thank you!
