### ISSUE TITLE
Issue with Vue monorepo

### ISSUE THREAD

**Issue by nguyenbatranvan** [nguyenbatranvan/vite-multiple-assets#24]

**Comment by nguyenbatranvan** [comment]
@zhixiaotong i tried fork your repo, both dev and prod environment work fine, images are fully displayed. what is the problem here?

**Comment by zhixiaotong** [comment]
Thx. I pushed changes to https://github.com/zhixiaotong/monorepo-assets-demo, picrtures in folder `a` and `b` dont display.
![image](https://github.com/user-attachments/assets/c4ea3374-ce8b-451a-a774-b39b9f36459b)

**Comment by zhixiaotong** [comment]
After `build`, preview works fine.

**Comment by nguyenbatranvan** [comment]
I have tested your repo in dev now, and it displays perfectly on browsers, chrome, safari, fireox,..

<img width="1114" alt="image" src="https://github.com/user-attachments/assets/1d8fdac9-820a-4afa-bbff-97827a63a0ec">

**Comment by nguyenbatranvan** [comment]
safari
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/b95f7a2b-d959-426a-aaf3-f7bee16f94aa">

**Comment by zhixiaotong** [comment]
![20241106102008_rec_](https://github.com/user-attachments/assets/8a949056-2e5e-4cf7-8ffd-47376e33aa26)
This... is so strange.I am using Google Chrome.

**Comment by nguyenbatranvan** [comment]
> ![20241106102008_rec_](https://private-user-images.githubusercontent.com/34681550/383383827-8a949056-2e5e-4cf7-8ffd-47376e33aa26.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjAwNDksIm5iZiI6MTczMDg1OTc0OSwicGF0aCI6Ii8zNDY4MTU1MC8zODMzODM4MjctOGE5NDkwNTYtMmU1ZS00Y2Y3LThmZmQtNDczNzZlMzNhYTI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYWQ2MGU1ZTEzMTJmZDEwMmI5Y2U4ODk1ZTk1NjgwYTU2YTJlZTNmYmM5NDE4YmI5NWQ3ZGJhNzNlMjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twPh80JyDR1JR4kufmRjkfM1N11IIF219fiM6YfFcbw) [ ![20241106102008_rec_](https://private-user-images.githubusercontent.com/34681550/383383827-8a949056-2e5e-4cf7-8ffd-47376e33aa26.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjAwNDksIm5iZiI6MTczMDg1OTc0OSwicGF0aCI6Ii8zNDY4MTU1MC8zODMzODM4MjctOGE5NDkwNTYtMmU1ZS00Y2Y3LThmZmQtNDczNzZlMzNhYTI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYWQ2MGU1ZTEzMTJmZDEwMmI5Y2U4ODk1ZTk1NjgwYTU2YTJlZTNmYmM5NDE4YmI5NWQ3ZGJhNzNlMjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twPh80JyDR1JR4kufmRjkfM1N11IIF219fiM6YfFcbw) ](https://private-user-images.githubusercontent.com/34681550/383383827-8a949056-2e5e-4cf7-8ffd-47376e33aa26.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjAwNDksIm5iZiI6MTczMDg1OTc0OSwicGF0aCI6Ii8zNDY4MTU1MC8zODMzODM4MjctOGE5NDkwNTYtMmU1ZS00Y2Y3LThmZmQtNDczNzZlMzNhYTI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYWQ2MGU1ZTEzMTJmZDEwMmI5Y2U4ODk1ZTk1NjgwYTU2YTJlZTNmYmM5NDE4YmI5NWQ3ZGJhNzNlMjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twPh80JyDR1JR4kufmRjkfM1N11IIF219fiM6YfFcbw) [ ](https://private-user-images.githubusercontent.com/34681550/383383827-8a949056-2e5e-4cf7-8ffd-47376e33aa26.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NjAwNDksIm5iZiI6MTczMDg1OTc0OSwicGF0aCI6Ii8zNDY4MTU1MC8zODMzODM4MjctOGE5NDkwNTYtMmU1ZS00Y2Y3LThmZmQtNDczNzZlMzNhYTI2LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDAyMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYWQ2MGU1ZTEzMTJmZDEwMmI5Y2U4ODk1ZTk1NjgwYTU2YTJlZTNmYmM5NDE4YmI5NWQ3ZGJhNzNlMjAxZTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.twPh80JyDR1JR4kufmRjkfM1N11IIF219fiM6YfFcbw) This... is so strange.I am using Google Chrome 130.0.6723.92.

if possible, please help me with the following:
1. Clear cache or open anonymous tab chrome
2. Run server with different port, for example: 3000

**Comment by nguyenbatranvan** [comment]
And can you tell me what operating system your computer is running?

**Comment by zhixiaotong** [comment]
> And can you tell me what operating system your computer is running?

window11

**Comment by nguyenbatranvan** [comment]
> > And can you tell me what operating system your computer is running?
> 
> windows11

I just tried it on windows 10, 11 and macos and it runs stably.

**Comment by zhixiaotong** [comment]
I tried again, deleted the node_modules and downloaded it again, cleared the browser cache, and still got the same result.I'm confused. /(ㄒoㄒ)/~~
![image](https://github.com/user-attachments/assets/9830ee8c-75c8-4d8a-9429-4472fb1b989a)

**Comment by nguyenbatranvan** [comment]
> I tried again, deleted the node_modules and downloaded it again, cleared the browser cache, and still got the same result.I'm confused. /(ㄒoㄒ)/~~

try change port serve & open anonymous tab:

![image](https://github.com/user-attachments/assets/77225356-9c14-4ccf-8aae-3dfe4739f98c)

**Comment by zhixiaotong** [comment]
> > I tried again, deleted the node_modules and downloaded it again, cleared the browser cache, and still got the same result.I'm confused. /(ㄒoㄒ)/~~
> 
> try change port serve & open anonymous tab:
> 
> ![image](https://github.com/user-attachments/assets/77225356-9c14-4ccf-8aae-3dfe4739f98c)
> 
I also tried. I asked my colleague to help clone the repository and run it locally. His result is the same as mine.
![1730861755727.jpg](https://github.com/user-attachments/assets/4fdf9773-3ce0-4228-b1df-32da81be5197)

**Comment by nguyenbatranvan** [comment]
Okay, I think there is a problem if running the code from windows. Unlike me, running the code from macos and opening on windows operating system. Maybe, `join` on windows works differently. I don't have windows operating system to run my library code. So I might try to come up with a fix, if it doesn't work, give me a chat connection with you, and you can help me solve this problem

**Comment by nguyenbatranvan** [comment]
Now!! Please help me version: `2.0.2`

**Comment by zhixiaotong** [comment]
> Okay, I think there is a problem if running the code from windows. Unlike me, running the code from macos and opening on windows operating system. Maybe, `join` on windows works differently. I don't have windows operating system to run my library code. So I might try to come up with a fix, if it doesn't work, give me a chat connection with you, and you can help me solve this problem

with pleasure

**Comment by zhixiaotong** [comment]
> Now!! Please help me version: `2.0.2`

ok

**Comment by zhixiaotong** [comment]
> > Now!! Please help me version: `2.0.2`
> 
> ok

Nice!!! Both dev and build works normally.

**Comment by nguyenbatranvan** [comment]
> > > Now!! Please help me version: `2.0.2`
> > 
> > 
> > ok
> 
> Nice!!! Both dev and build works normally.

Thanks for reporting this issue!! Otherwise windows users will face the problem!!

**Comment by zhixiaotong** [comment]
Thanks for the fix, now I can use this plugin to solve the bloated problem! ^_^

**Comment by nguyenbatranvan** [comment]
@zhixiaotong LOLLL!! I have a mistake about the version, it should be `2.1.2` =))

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Hi, here I am again. I found that if I add the `base` attribute to `vite.config.ts`, the picture cannot be displayed. Is it because the plugin does not support `base` now or is it a problem for me to use? Thanks.
![image](https://github.com/user-attachments/assets/13e779fb-4ebc-4f7b-b812-13ae55932073)

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan Hi, here I am again. I found that if I add the `base` attribute to `vite.config.ts`, the picture cannot be displayed. Is it because the plugin does not support `base` now or is it a problem for me to use? Thanks. ![image](https://private-user-images.githubusercontent.com/34681550/385702551-2874d12e-c15c-4c16-a94b-b753473df527.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTIxMTEsIm5iZiI6MTczMTQ5MTgxMSwicGF0aCI6Ii8zNDY4MTU1MC8zODU3MDI1NTEtMjg3NGQxMmUtYzE1Yy00YzE2LWE5NGItYjc1MzQ3M2RmNTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDA5NTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYzUwYTE4NDM5ZWJkYzBiZjAyMWRmYjcxOGY5MmEyMGY4Y2U5OGQxNDhmZjRmOTQ3YTE0ZTllZWZkY2NjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ya7SomJfAamrOXVnVbFoLU1Dnc6KHi6B6lyP3RLkiwo)

i think it's a bug!! find a way to put base in router of 3rd party library first. i will look into this tomorrow!! thanks for reporting

**Comment by nguyenbatranvan** [comment]
Please create another issue for me, if you can. hhhh!!

**Comment by zhixiaotong** [comment]
> Please create another issue for me, if you can. hhhh!!

ok
