### ISSUE TITLE
Rollup failed to resolve import

### ISSUE THREAD

**Issue by AKclown** [nguyenbatranvan/vite-multiple-assets#26]
Scenario Description：

I just used pnpm workspace to build multiple subsystems. The subsystems have some common components and icons. When I use DynamicPublicDirectory to set the public file directory, I can access 404.png normally in the development environment, but when I package, the 404.png file is not found.

File Structure：
![image](https://github.com/user-attachments/assets/af35e08b-55d5-4b73-a702-0c08a41899ac)

My configuration information: 
![image](https://github.com/user-attachments/assets/c6e3dea2-7608-449a-ac52-f956ad634a47)

```ts
"vite-multiple-assets": "^2.1.2",
"vue": "^3.4.37",
"vite": "^5.4.1"
```

Thanks for the plugin, can you give me some suggestions?

**Comment by nguyenbatranvan** [comment]
vue3 public mechanism will be different from React, Solid,.. I have an example of this [here](https://github.com/nguyenbatranvan/vite-multiple-assets/blob/main/packages/examples/vue3/vite.config.ts). There will be configuration:

```
vue({
        template:{
            transformAssetUrls:{
                img: [''],
            }
        }
    })
```
Or another way I would like to suggest you is to use createUrl like in [this repo](https://github.com/zhixiaotong/monorepo-assets-demo/blob/main/apps/a/src/TestA.vue).

**Comment by AKclown** [comment]
Thanks,
```ts
vue({
        template:{
            transformAssetUrls:{
                img: [''],
            }
        }
    })
```
This method solves this problem
