### ISSUE TITLE
picture not displayed using `base` in `vite.config.ts`

### ISSUE THREAD

**Issue by zhixiaotong** [nguyenbatranvan/vite-multiple-assets#29]
I found that if I add the `base` attribute to `vite.config.ts`, the picture cannot be displayed. Is it because the plugin does not support `base` now or is it a problem for me to use? Thanks.
![image](https://github.com/user-attachments/assets/2874d12e-c15c-4c16-a94b-b753473df527)
The path of the image should be `http://{domain}/{base}/static/svgs/analytics/bg.svg`, not `http://{domain}/static/svgs/analytics/bg.svg`

**Comment by zhixiaotong** [comment]
I also added the `base` in the `vue-router` configuration. The two have different functions. The `base` in the vite configuration will affect all static resources and also the structure of the generated dist directory.

**Comment by nguyenbatranvan** [comment]
i have looked into this, it seems that links that do not start with `vite base` will not go through my library. So i will need some time to figure out how `vite base `works

**Comment by zhixiaotong** [comment]
Perhaps the plugin requires the support of the `base` attribute. The default `base` in Vite is "/", and this attribute is used very frequently. Thank you for devoting your time and energy to this.

**Comment by nguyenbatranvan** [comment]
I have reviewed Vite's `base` configuration. The image sources (src) that do not begin with the base configured in `Vite` will not pass through my plugin. Additionally, I haven't found a way to configure the transformation of those links within the images. You might need something simple like this:

`vite.config.ts`

```
export default defineConfig({
    base:"/ts/",
    ....
})
```

inside component:

```
<img aria-label={"logo-assets"} src={"/ts/shared/images/vite.svg"} className="logo" alt="Vite logo"/>
```

If I proceed this way, I might need to adjust my plugin a bit. If there were a way to modify the `image` src, adding the `base` before loading, things could be simpler. However, at the moment, it seems impossible.

**Comment by zhixiaotong** [comment]
En... I agree, things are not that easy, in practice, the production environment may deploy different `env` environment variables to achieve different packaging effects, it is not realistic to fix the address base of each asset resource in html or ts.

**Comment by zhixiaotong** [comment]
Got it, looking forward to good news.

**Comment by nguyenbatranvan** [comment]
maybe not today! Because I'm quite busy with my work. Will be tomorrow or at the latest by the end of the week!!! LOLLL

**Comment by nguyenbatranvan** [comment]
I released version `2.1.3 `for this issue, `production` mode still works fine, just some library tweaks for `development` mode

**Comment by zhixiaotong** [comment]
> I released version `2.1.3` for this issue, `production` mode still works fine, just some library tweaks for `development` mode. The `e2e tests` for `base` and no use cases are both successful [here](https://github.com/nguyenbatranvan/vite-multiple-assets/actions/runs/11849682579/job/33023341740). I think you can use it with confidence.

thx!!! I'll try it later.

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Is it possible to solve the problem of automatically generating the base prefix for the image address declared in CSS?
![image](https://github.com/user-attachments/assets/ca28126c-2328-4ca0-96c9-a3ca62f61836)

**Comment by nguyenbatranvan** [comment]
I think you will add `base` before image of css yourself

**Comment by zhixiaotong** [comment]
> I think you will add `base` before image of css yourself

This is indeed a solution, but we need to package the processing according to different bases, which is impossible.

**Comment by zhixiaotong** [comment]
The `base` attribute in the `vite` configuration itself handles the css and adds the base prefix to the image. In my project, most **static resources** are displayed through css, and only a small part is displayed through the `new URL`.

![image](https://github.com/user-attachments/assets/ad1c5db2-b0cb-4d11-bec0-aae671864cbf)

![image](https://github.com/user-attachments/assets/ce81df32-f14c-4936-a547-4ad6757f47b9)

**Comment by nguyenbatranvan** [comment]
For now, address it by manually adding the `base` to the CSS. I’ll review` Vite’s transform`, check for paths matching `assets` provided to the `plugin`, and add the `base` accordingly. This might take some time!

**Comment by nguyenbatranvan** [comment]
> > En... I agree, things are not that easy, in practice, the production environment may deploy different `env` environment variables to achieve different packaging effects, it is not realistic to fix the address base of each asset resource in html or ts.
> 
> I’ve found a way to replace the src of the img, but it doesn’t seem to be very optimized in terms of performance! Not to mention, each library has a different syntax for how to represent src. For now, I will propose solving it using the method above! If anything comes up with this approach later, I might implement this solution. I will let you know when it is completed.

Maybe the way I said it before!! LOLLL

**Comment by zhixiaotong** [comment]
> For now, address it by manually adding the `base` to the CSS. I’ll review` Vite’s transform`, check for paths matching `assets` provided to the `plugin`, and add the `base` accordingly. This might take some time!

LOL, thank you for your contribution to this, it is indeed a very useful feature for me.But it is difficult for me to help you at present, and it is sad...

**Comment by nguyenbatranvan** [comment]
> > For now, address it by manually adding the `base` to the CSS. I’ll review` Vite’s transform`, check for paths matching `assets` provided to the `plugin`, and add the `base` accordingly. This might take some time!
> 
> LOL, thank you for your contribution to this, it is indeed a very useful feature for me.But it is difficult for me to help you at present, and it is sad...

Don't worry; it's my pleasure to contribute to solving any issues. Let me know if there are any other problems, and I’ll try to address any outstanding concerns as soon as possible. Thank you!

**Comment by zhixiaotong** [comment]
There are no other problems for the time being. You may need to pay attention to the relative path of the picture in css. Replacing the picture address in css is limited to the resolved static address. The relative path will be specially handled in the development environment, and the address will be hashed after build.

**Comment by nguyenbatranvan** [comment]
> There are no other problems for the time being. You may need to pay attention to the relative path of the picture in css. Replacing the picture address in css is limited to the resolved static address. The relative path will be specially handled in the development environment, and the address will be hashed after build.
> 
> ![image](https://private-user-images.githubusercontent.com/34681550/387922911-fa9cf7bd-a078-4d6f-84c7-7dee57d3a450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQ5NzMsIm5iZiI6MTczMjA3NDY3MywicGF0aCI6Ii8zNDY4MTU1MC8zODc5MjI5MTEtZmE5Y2Y3YmQtYTA3OC00ZDZmLTg0YzctN2RlZTU3ZDNhNDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOWUwYjE3NTRhODVlMzFjOTAyZjE1Yjk1Y2RmMmZlMTlkM2UyM2MwYTAyMTJjY2QzYTgyODc4NWFlYjYwMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FocBVywY6Xge4gTbckDJmYCF9LC8uGX08Y4S0um712Q)
> 
> ### dev
> ![image](https://private-user-images.githubusercontent.com/34681550/387923046-1f869765-2d39-482a-8353-960faafae862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQ5NzMsIm5iZiI6MTczMjA3NDY3MywicGF0aCI6Ii8zNDY4MTU1MC8zODc5MjMwNDYtMWY4Njk3NjUtMmQzOS00ODJhLTgzNTMtOTYwZmFhZmFlODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmQyNWM1NTVhYjkzNzFmNzYxZjNhODEwZDQ2OTUwMDM2YjhiZGRhZDhjMWQ3NTFjMGU5NjQ5OTI1ODYxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPdjDMByYtTxaVtyptwsPqPew3K1SkKsTNu3SHiPcdo)
> 
> ### build
> ![image](https://private-user-images.githubusercontent.com/34681550/387923220-cff09eb6-1005-4e27-9721-f738dae3b23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQ5NzMsIm5iZiI6MTczMjA3NDY3MywicGF0aCI6Ii8zNDY4MTU1MC8zODc5MjMyMjAtY2ZmMDllYjYtMTAwNS00ZTI3LTk3MjEtZjczOGRhZTNiMjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOTkzZDRmMzliYjgwODk3NzA0ZDZiZmE5MDEzYWEyZWVmNGIyNTZhNzAwMWM1ZmM1ZmY4Y2VhMTRlNGZiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J2XsnN-u3uqdK5wSISKYJekVkxiEz6jvCvJ0D0KHL4c)

What I will be doing in the future will be something like this:

```
transform(code, id) {
    if(!opts.needTransformBase){
      return null;
    }
    if (/\.(css|scss|sass|less|styl|stylus)$/.test(id)) {
        return {
            code: code.replace(/background(-image)?:.*url\(["']?([^"')]+)["']?\)/g, (match, _, url) => {
                // todo find path in assets 
                // newPath = viteConfig.base + findPath
                const newUrl = url.replace(oldPath, newPath);
                return match.replace(url, newUrl);
            }),
        };
    }
    return null;
}
```

Of course to ensure performance, I will need to add an options:

```
DynamicPublicDirectory(assets, {
            needTransformBase: true
        })
```

**Comment by zhixiaotong** [comment]
> > There are no other problems for the time being. You may need to pay attention to the relative path of the picture in css. Replacing the picture address in css is limited to the resolved static address. The relative path will be specially handled in the development environment, and the address will be hashed after build.
> > ![image](https://private-user-images.githubusercontent.com/34681550/387922911-fa9cf7bd-a078-4d6f-84c7-7dee57d3a450.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQ5NzMsIm5iZiI6MTczMjA3NDY3MywicGF0aCI6Ii8zNDY4MTU1MC8zODc5MjI5MTEtZmE5Y2Y3YmQtYTA3OC00ZDZmLTg0YzctN2RlZTU3ZDNhNDUwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlOWUwYjE3NTRhODVlMzFjOTAyZjE1Yjk1Y2RmMmZlMTlkM2UyM2MwYTAyMTJjY2QzYTgyODc4NWFlYjYwMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FocBVywY6Xge4gTbckDJmYCF9LC8uGX08Y4S0um712Q)
> > ### dev
> > ![image](https://private-user-images.githubusercontent.com/34681550/387923046-1f869765-2d39-482a-8353-960faafae862.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQ5NzMsIm5iZiI6MTczMjA3NDY3MywicGF0aCI6Ii8zNDY4MTU1MC8zODc5MjMwNDYtMWY4Njk3NjUtMmQzOS00ODJhLTgzNTMtOTYwZmFhZmFlODYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhYmQyNWM1NTVhYjkzNzFmNzYxZjNhODEwZDQ2OTUwMDM2YjhiZGRhZDhjMWQ3NTFjMGU5NjQ5OTI1ODYxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.YPdjDMByYtTxaVtyptwsPqPew3K1SkKsTNu3SHiPcdo)
> > ### build
> > ![image](https://private-user-images.githubusercontent.com/34681550/387923220-cff09eb6-1005-4e27-9721-f738dae3b23c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIwNzQ5NzMsIm5iZiI6MTczMjA3NDY3MywicGF0aCI6Ii8zNDY4MTU1MC8zODc5MjMyMjAtY2ZmMDllYjYtMTAwNS00ZTI3LTk3MjEtZjczOGRhZTNiMjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDAzNTExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhOTkzZDRmMzliYjgwODk3NzA0ZDZiZmE5MDEzYWEyZWVmNGIyNTZhNzAwMWM1ZmM1ZmY4Y2VhMTRlNGZiNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.J2XsnN-u3uqdK5wSISKYJekVkxiEz6jvCvJ0D0KHL4c)
> 
> What I will be doing in the future will be something like this:
> 
> ```
> transform(code, id) {
>     if(!opts.needTransformBase){
>       return null;
>     }
>     if (/\.(css|scss|sass|less|styl|stylus)$/.test(id)) {
>         return {
>             code: code.replace(/background(-image)?:.*url\(["']?([^"')]+)["']?\)/g, (match, _, url) => {
>                 // todo find path in assets 
>                 // newPath = viteConfig.base + findPath
>                 const newUrl = url.replace(oldPath, newPath);
>                 return match.replace(url, newUrl);
>             }),
>         };
>     }
>     return null;
> }
> ```
> 
> Of course to ensure performance, I will need to add an options:
> 
> ```
> DynamicPublicDirectory(assets, {
>             needTransformBase: true
>         })
> ```
The path of some imgs is not the `assets` directory set passed by the `DynamicPublicDirectory`, and the address should not be converted. I don't know what conversion logic `vite` takes by default. When the image address is not a static resource directory, it should be compiled instead of copied.

**Comment by nguyenbatranvan** [comment]
`DynamicPublicDirectory` is only responsible for searching and replacing paths that are in its `assets`! For static urls that are not in `assets`, it will work as it does now with `vite`

**Comment by zhixiaotong** [comment]
> `DynamicPublicDirectory` is only responsible for searching and replacing paths that are in its `assets`! For static urls that are not in `assets`, it will work as it does now with `vite`

I see. ^ ^

**Comment by nguyenbatranvan** [comment]
I have created a PR for this issue, it passed the tests, I will take a closer look at it for release in the next few days

**Comment by zhixiaotong** [comment]
Brilliant work!LOLLLLL!!!

**Comment by nguyenbatranvan** [comment]
released `2.2.2`. Pls check again!

**Comment by zhixiaotong** [comment]
> released `2.2.2`. Pls check again!

Ok, I'll test it in an hour or two, I'm out of space right now ^^

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Everything is running normally, both dev and build can display pictures! But when I run the `pnpm build` command, the console will print out, while there will be a lot of css pictures used in the actual project, which may cause the console to output a lot.
![image](https://github.com/user-attachments/assets/b9094237-0715-4b6b-9058-be2832cb847e)

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan Everything is running normally, both dev and build can display pictures! But when I run the `pnpm build` command, the console will print out, while there will be a lot of css pictures used in the actual project, which may cause the console to output a lot. ![image](https://private-user-images.githubusercontent.com/34681550/388877399-b9094237-0715-4b6b-9058-be2832cb847e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjc1NjcsIm5iZiI6MTczMjI2NzI2NywicGF0aCI6Ii8zNDY4MTU1MC8zODg4NzczOTktYjkwOTQyMzctMDcxNS00YjZiLTkwNTgtYmUyODMyY2I4NDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5MjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmN2UyNzIxODYxNDcxMWViNTE1NTBmODI1MzA0ZGE0YzAwYzE2NjA1YjlkODAxNzQ2NTNjMWFiNTRhNTAwYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8QCf91d1VtA5Nc_xFjdIaIkHXuLEBZbHB4AwJGyVgjE)

This warning is triggered by `Vite`. There might be an option in `Vite` to suppress this warning.

**Comment by zhixiaotong** [comment]
Oh, there's a little problem here. @nguyenbatranvan 

### Normal both `dev` and `build`

```ts
plugins: [
    vue(),
    DynamicPublicDirectory([
      'apps/shared/assets/**',
      // use separate assets folder for each app
      {input: 'apps/a/src/assets/**', output: 'static/assets-a'},
      {input: 'apps/b/src/assets/**', output: 'static/assets-b'}
    ],{
      cwd: process.cwd(),
      needTransformBaseCss: true
    })
  ],
```
![image](https://github.com/user-attachments/assets/8357220f-8db8-43b1-9f6d-56cb9922581b)


### Abnormal `dev`, but normal with `build`

```ts
plugins: [
    vue(),
    DynamicPublicDirectory([
      {input: 'apps/shared/assets/static/**', output: 'static/shared'},
      // use separate assets folder for each app
      {input: 'apps/a/src/assets/**', output: 'static/assets-a'},
      {input: 'apps/b/src/assets/**', output: 'static/assets-b'}
    ],{
      cwd: process.cwd(),
      needTransformBaseCss: true
    })
  ],
```
![image](https://github.com/user-attachments/assets/c3500c34-ac35-41fa-91ba-7212b5498521)
![image](https://github.com/user-attachments/assets/4a3f9ef7-fbba-4d9c-8818-9a43952d1630)

**Comment by zhixiaotong** [comment]
> > @nguyenbatranvan Everything is running normally, both dev and build can display pictures! But when I run the `pnpm build` command, the console will print out, while there will be a lot of css pictures used in the actual project, which may cause the console to output a lot. ![image](https://private-user-images.githubusercontent.com/34681550/388877399-b9094237-0715-4b6b-9058-be2832cb847e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjc1NjcsIm5iZiI6MTczMjI2NzI2NywicGF0aCI6Ii8zNDY4MTU1MC8zODg4NzczOTktYjkwOTQyMzctMDcxNS00YjZiLTkwNTgtYmUyODMyY2I4NDdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5MjEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNmN2UyNzIxODYxNDcxMWViNTE1NTBmODI1MzA0ZGE0YzAwYzE2NjA1YjlkODAxNzQ2NTNjMWFiNTRhNTAwYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.8QCf91d1VtA5Nc_xFjdIaIkHXuLEBZbHB4AwJGyVgjE)
> 
> This warning is triggered by `Vite`. There might be an option in `Vite` to suppress this warning.

I'll go through the vite documentation carefully to avoid these warnings, too annoying~

**Comment by nguyenbatranvan** [comment]
> Oh, there's a little problem here. @nguyenbatranvan
> 
> ### Normal both `dev` and `build`
> ```ts
> plugins: [
>     vue(),
>     DynamicPublicDirectory([
>       'apps/shared/assets/**',
>       // use separate assets folder for each app
>       {input: 'apps/a/src/assets/**', output: 'static/assets-a'},
>       {input: 'apps/b/src/assets/**', output: 'static/assets-b'}
>     ],{
>       cwd: process.cwd(),
>       needTransformBaseCss: true
>     })
>   ],
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/34681550/388879302-8357220f-8db8-43b1-9f6d-56cb9922581b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjc5MzUsIm5iZiI6MTczMjI2NzYzNSwicGF0aCI6Ii8zNDY4MTU1MC8zODg4NzkzMDItODM1NzIyMGYtOGRiOC00M2IxLTlmNmQtNTZjYjk5MjI1ODFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg1MDMxOTJlMWU4YTVhODJkNjRmNGIwZDM2ZjA1MzZhNTZhOGY4MTYyN2Q4MDU0MzJhYzYxOGMzNzhhMTIzNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.qTtX9BK38VsiiotCMFmFq4s7fyM08BgufdF8q75cxrA)
> 
> ### Abnormal `dev`, but normal with `build`
> ```ts
> plugins: [
>     vue(),
>     DynamicPublicDirectory([
>       {input: 'apps/shared/assets/static/**', output: 'static/shared'},
>       // use separate assets folder for each app
>       {input: 'apps/a/src/assets/**', output: 'static/assets-a'},
>       {input: 'apps/b/src/assets/**', output: 'static/assets-b'}
>     ],{
>       cwd: process.cwd(),
>       needTransformBaseCss: true
>     })
>   ],
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/34681550/388879189-c3500c34-ac35-41fa-91ba-7212b5498521.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjc5MzUsIm5iZiI6MTczMjI2NzYzNSwicGF0aCI6Ii8zNDY4MTU1MC8zODg4NzkxODktYzM1MDBjMzQtYWMzNS00MWZhLTkxYmEtNzIxMmI1NDk4NTIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhOTNlYmVmZTk1MTFmZmJkM2U3ZWU2YWUzOTZmMGYzYzYzOTc2ZGVlNTYxOTQwZDBmNTQxZjVkZGE3NWIwNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NYeO_Hsw88ccVLEIbC4PdfQEstSwYvwxX_Md-7jMVDs) ![image](https://private-user-images.githubusercontent.com/34681550/388880250-4a3f9ef7-fbba-4d9c-8818-9a43952d1630.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIyNjc5MzUsIm5iZiI6MTczMjI2NzYzNSwicGF0aCI6Ii8zNDY4MTU1MC8zODg4ODAyNTAtNGEzZjllZjctZmJiYS00ZDljLTg4MTgtOWE0Mzk1MmQxNjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIyVDA5MjcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjNjFkNGI4YjdmNzNlMzMwYWE2MDQyMjAzZThlOTU5YjBhZGYyMzNiZWUwZDc1NjdmODBjNTcxZmFiM2IzODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.WPJ9_BE02gKwlK4XJpGR_WS7DaeGE9Sxx9W4xNDCPFY)

You can push the code to your repository, and I’ll check it.

**Comment by zhixiaotong** [comment]
I just pushed it.

**Comment by nguyenbatranvan** [comment]
It seems to be running fine on my machine. I’m wondering if the issue only occurs on Windows OS?


<img width="443" alt="image" src="https://github.com/user-attachments/assets/6eb28dbe-5206-4a0e-a894-8b05058e25db">

**Comment by zhixiaotong** [comment]
I guess so, only happens in dev.

**Comment by nguyenbatranvan** [comment]
Okay. I’ll run some tests on Windows and will figure out the issue soon

**Comment by zhixiaotong** [comment]
I'll be out this weekend. If you make changes before next Monday, I can only verify it on Monday. Sorry.

**Comment by nguyenbatranvan** [comment]
Let me clarify: with your current repository, the background image is not displayed as it should be, based on the results I sent?

**Comment by nguyenbatranvan** [comment]
This thread is too long, I will move to this [issue](https://github.com/nguyenbatranvan/vite-multiple-assets/issues/38)

**Comment by zhixiaotong** [comment]
> Let me clarify: with your current repository, the background image is not displayed as it should be, based on the results I sent?

yes,only backgrnotdisplayed displayed
