### ISSUE TITLE
Background image css not dislay on window OS

### ISSUE THREAD

**Issue by nguyenbatranvan** [nguyenbatranvan/vite-multiple-assets#38]

**Comment by nguyenbatranvan** [comment]
I’m not sure what the issue is! Your source runs fine on my machine, and I suspect it’s related to the `OS`. That’s why I created `end-to-end` tests on `Windows` using `GitHub Actions`. Surprisingly, they passed without any issues.. See more test [here](https://github.com/nguyenbatranvan/vite-multiple-assets/actions/runs/11971951967/job/33377826590?pr=37)

**Comment by zhixiaotong** [comment]
That's really strange, but it is indeed the case in my computer's development environment.

**Comment by nguyenbatranvan** [comment]
> That's really strange, but it is indeed the case in my computer's development environment.

Alright, it’s the weekend—time to relax! I’ll provide a patch on Monday, but I’m a bit unsure about it, so I’ll just fix it based on my intuition. 😅

**Comment by zhixiaotong** [comment]
> > That's really strange, but it is indeed the case in my computer's development environment.
> 
> Alright, it’s the weekend—time to relax! I’ll provide a patch on Monday, but I’m a bit unsure about it, so I’ll just fix it based on my intuition. 😅

Yes. It shouldn't be a big problem.

**Comment by zhixiaotong** [comment]
I'm back, back to work.

**Comment by zhixiaotong** [comment]
I see the reason, does the plugin currently not support `hmr`? Once I change `vite.config.ts`, the image loading path is not updated, I need to restart the dev command.

**Comment by zhixiaotong** [comment]
> > > That's really strange, but it is indeed the case in my computer's development environment.
> > 
> > 
> > Alright, it’s the weekend—time to relax! I’ll provide a patch on Monday, but I’m a bit unsure about it, so I’ll just fix it based on my intuition. 😅
> 
> Yes. It shouldn't be a big problem.

The path is normal. It was caused by me changing the `vite` configuration but not restarting the dev command.

**Comment by nguyenbatranvan** [comment]
> I see the reason, does the plugin currently not support `hmr`? Once I change `vite.config.ts`, the image loading path is not updated, I need to restart the dev command.

The HMR mechanism triggered by changes in vite.config.ts is controlled by Vite, and my plugin cannot interfere with it. Currently, the plugin only supports re-running when changes are made to the observed input files. U can see option `watch` at [here](https://nguyenbatranvan.github.io/vite-multiple-assets-doc/guide/index.html#custom-output-assets)

**Comment by nguyenbatranvan** [comment]
v `2.2.3` is released. About 5 minutes before your issue is resolved =))

**Comment by zhixiaotong** [comment]
> v `2.2.3` is released. About 5 minutes before your issue is resolved =))

I tested it, I looked at the source code, and watch seems to only respond to changes in the image path, but in fact, the configuration file may have also changed. I changed the configuration file from `{'input': 'apps/shared/assets/static/**', output: 'static/shared', watch: true}` to `{'input': 'apps/shared/assets/**', output: '', watch: true},`

**Comment by zhixiaotong** [comment]
> > v `2.2.3` is released. About 5 minutes before your issue is resolved =))
> 
> I tested it, I looked at the source code, and watch seems to only respond to changes in the image path, but in fact, the configuration file may have also changed. I changed the configuration file from `{'input': 'apps/shared/assets/static/**', output: 'static/shared', watch: true}` to `{'input': 'apps/shared/assets/**', output: '', watch: true},`. If the `input` or `output` of the configuration changes, can the restart be avoided to achieve the goal?

**Comment by nguyenbatranvan** [comment]
> > > v `2.2.3` is released. About 5 minutes before your issue is resolved =))
> > 
> > 
> > I tested it, I looked at the source code, and watch seems to only respond to changes in the image path, but in fact, the configuration file may have also changed. I changed the configuration file from `{'input': 'apps/shared/assets/static/**', output: 'static/shared', watch: true}` to `{'input': 'apps/shared/assets/**', output: '', watch: true},`. If the `input` or `output` of the configuration changes, can the restart be avoided to achieve the goal?

 Think it will be supported, but there might be a release in the next few days. For now, please bear with restarting. Thank you!

**Comment by zhixiaotong** [comment]
> > > > v `2.2.3` is released. About 5 minutes before your issue is resolved =))
> > > 
> > > 
> > > I tested it, I looked at the source code, and watch seems to only respond to changes in the image path, but in fact, the configuration file may have also changed. I changed the configuration file from `{'input': 'apps/shared/assets/static/**', output: 'static/shared', watch: true}` to `{'input': 'apps/shared/assets/**', output: '', watch: true},`. If the `input` or `output` of the configuration changes, can the restart be avoided to achieve the goal?
> 
> Think it will be supported, but there might be a release in the next few days. For now, please bear with restarting. Thank you!

Of course no problem, in general, this plugin has achieved the effect I want, thank you. I will also recommend this plugin in the Chinese community later, hoping to help more developers with this need. LOLLLL

**Comment by nguyenbatranvan** [comment]
You're very welcome

**Comment by nguyenbatranvan** [comment]
i think i will close this issue

**Comment by nguyenbatranvan** [comment]
Hi!! Version `2.2.4` released

**Comment by zhixiaotong** [comment]
> Hi!! Version `2.2.4` released

`hmr` fixed?

**Comment by nguyenbatranvan** [comment]
> > Hi!! Version `2.2.4` released
> 
> `hmr` fixed?

yess

**Comment by zhixiaotong** [comment]
> > > Hi!! Version `2.2.4` released
> > 
> > 
> > `hmr` fixed?
> 
> yess

Thx for your work on this!

**Comment by zhixiaotong** [comment]
@nguyenbatranvan I tried the `2.2.4` version, but the css picture still doesn't work with `hmr`.

https://github.com/user-attachments/assets/6cdead42-54ba-4f1c-b7e0-5d4fb4f1a407

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan I tried the `2.2.4` version, but the css picture still doesn't work with `hmr`.
> 
>  20241128-113713.mp4

Hmm, it's not an issue with `HMR`. Currently, for `CSS`, I cache the data on the first load. On subsequent changes, if the data is already cached, `getFiles` won't be called again. Perhaps I should implement caching for both the old and new options to handle this better.

**Comment by zhixiaotong** [comment]
@nguyenbatranvan Hi, when I pasted the image from outside into the project, the console reported an error. I need restart dev.
![image](https://github.com/user-attachments/assets/8e0b79b7-aa82-42c2-bcb6-c5ec558c7371)

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan Hi, when I pasted the image from outside into the project, the console reported an error. I need to restart the project. ![image](https://private-user-images.githubusercontent.com/34681550/392267628-8e0b79b7-aa82-42c2-bcb6-c5ec558c7371.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyOTc2NjYsIm5iZiI6MTczMzI5NzM2NiwicGF0aCI6Ii8zNDY4MTU1MC8zOTIyNjc2MjgtOGUwYjc5YjctYWE4Mi00MmMyLWJjYjYtYzVlYzU1OGM3MzcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDA3MjkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4M2YxOWI2MWRmMTFhY2ViN2NiNWU5YWU5ZTU1NmE2ZjUzMzUwNTNjYTI1ZjhiMjk0Mjc3ZjkzMTZmOTgyNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Oz763FJEpOMChxRKIoOdnO67y05NEASg2uf_nd2rxus)

oke!! noted

**Comment by nguyenbatranvan** [comment]
See issue:

- [https://github.com/nguyenbatranvan/vite-multiple-assets/issues/43](https://github.com/nguyenbatranvan/vite-multiple-assets/issues/43)
