### ISSUE TITLE
Watch path error

### ISSUE THREAD

**Issue by nguyenbatranvan** [nguyenbatranvan/vite-multiple-assets#43]
when I pasted the image from outside into the project, the console reported an error. I need to restart the project.

![image](https://github.com/user-attachments/assets/eddafea5-770d-4ece-a6a8-15508feeac26)

**Comment by nguyenbatranvan** [comment]
@zhixiaotong I can't reproduce this issue in my project. Could there be some specific configuration causing it?

**Comment by nguyenbatranvan** [comment]
Please try version `2.2.5`. If it works, kindly help me close this issue.

**Comment by zhixiaotong** [comment]
> Please try version `2.2.5`. If it works, kindly help me close this issue.

Thx, I‘ll try it later.

**Comment by zhixiaotong** [comment]
@nguyenbatranvan I tried pasting and removing the picture a few times, and there is no error again. Vite reloads normally. ^_^
![image](https://github.com/user-attachments/assets/32bf75a4-a615-4a58-af9a-b106e7b00bce)

**Comment by nguyenbatranvan** [comment]
> @nguyenbatranvan I tried pasting and removing the picture a few times, and there is no error again. Vite reloads normally. ^_^ ![image](https://private-user-images.githubusercontent.com/34681550/398496913-32bf75a4-a615-4a58-af9a-b106e7b00bce.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMDUyMzAsIm5iZiI6MTczNTEwNDkzMCwicGF0aCI6Ii8zNDY4MTU1MC8zOTg0OTY5MTMtMzJiZjc1YTQtYTYxNS00YTU4LWFmOWEtYjEwNmU3YjAwYmNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI1VDA1MzUzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZTg0NmU3NTIzOGQyYWI2MzdlY2I1MTYyNGRiYTdiM2QwM2YxNzMxMDEwNWQwYTIxNmRlNjBiNDViMjBiZDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A0AR51lpP95PLfUG0dsRpNt7nilr2iHkOASBDkAP-5c)

tks so much!!
