### ISSUE TITLE
allow to extend and/or have default for mime types.

### ISSUE THREAD

**Issue by dirkbolte** [nguyenbatranvan/vite-multiple-assets#6]
I have a static asset without an extension (in my case , a file called `userinfo` as I'm mimicing an OIDC server ). In the default implementation, this results in the following error: `TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"`.

I ended up patching the package to add the file + content type I needed. 

It would be great if this plugin would provide the following functionalities:

- have a default mime type when none was found (instead of `undefined` + an error when running with `vite`)
- allow to overwrite said default
- add custom mime types
- extend mime type check to support the actual filename and/or a glob

**Comment by nguyenbatranvan** [comment]
> I have a static asset without an extension (in my case , a file called `userinfo` as I'm mimicing an OIDC server ). In the default implementation, this results in the following error: `TypeError [ERR_HTTP_INVALID_HEADER_VALUE]: Invalid value "undefined" for header "Content-Type"`.
> 
> I ended up patching the package to add the file + content type I needed.
> 
> It would be great if this plugin would provide the following functionalities:
> 
> * have a default mime type when none was found `instead of `undefined`+ an error when running with`vite`)
> * allow to overwrite said default
> * add custom mime types
> * extend mime type check to support the actual filename and/or a glob

What a great feature suggestion!! I will add that feature to the plugin soon. Thank you very much

**Comment by nguyenbatranvan** [comment]
greeting the new day! I have provided version `1.2.3`. You can extend the content type by adding config:
```
const dirAssets=["libs/assets","repo1/assets",...];
export default defineConfig({
    plugins: [
        DynamicPublicDirectory(dirAssets,{
            '.ac':'application/acc'
        })
    ]
})
```
I have added error handling, if the content type is not there it will be handled according to the [mime-types](https://www.npmjs.com/package/mime-types) library. You can try again, and if the problem is resolved, please help me close this issue!!

**Comment by dirkbolte** [comment]
thanks. Will take a bit but you will get feedback throughout the day.

**Comment by dirkbolte** [comment]
seems to work. Awesome!! Thanks for the quick reaction.

**Comment by nguyenbatranvan** [comment]
> seems to work. Awesome!! Thanks for the quick reaction.

tks so much!!!
