### ISSUE TITLE
Issue when converting vite.config to ESM syntax for Vite 6

### ISSUE THREAD

**Issue by Kingju777** [nguyenbatranvan/vite-multiple-assets#8]
Vite wants to remove CJS Support in Vite 6.0
Vite Warning in Vite 5.0: (The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.)

so i either need to have `"type": "module"` set in my package.json, or need to rename vite.config to `vite.config.mjs`.
but when i do that i get the following error:
```
failed to load config from C:\Users\[user]\Documents\[projekt]\vite.config.mts
error when starting dev server:
TypeError: DynamicPublicDirectory is not a function
    at file:///C:/Users/[user]/Documents/[projekt]/vite.config.mts.timestamp-1700214793206-f4bc32da7c83e.mjs:77:27
    at loadConfigFromFile (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:66134:15)
    at async resolveConfig (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:65735:28)
    at async _createServer (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:58325:20)
    at async CAC.<anonymous> (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/cli.js:764:24)       
 ELIFECYCLE  Command failed with exit code 1.
```
if i comment out DynamicPublicDirectory it works fine

<br>

<h4>Workaround:</h4>
Currently Vite is only warning, so it can simply be ignored or you can globaly activate "module" and rename vite.config to `vite.config.cjs`.

**Comment by nguyenbatranvan** [comment]
> Vite wants to remove CJS Support in Vite 6.0 Vite Warning in Vite 5.0: (The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.)
> 
> so i either need to have `"type": "module"` set in my package.json, or need to rename vite.config to `vite.config.mjs`. but when i do that i get the following error:
> 
> ```
> failed to load config from C:\Users\[user]\Documents\[projekt]\vite.config.mts
> error when starting dev server:
> TypeError: DynamicPublicDirectory is not a function
>     at file:///C:/Users/[user]/Documents/[projekt]/vite.config.mts.timestamp-1700214793206-f4bc32da7c83e.mjs:77:27
>     at loadConfigFromFile (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:66134:15)
>     at async resolveConfig (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:65735:28)
>     at async _createServer (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/chunks/dep-T98iZFpD.js:58325:20)
>     at async CAC.<anonymous> (file:///C:/Users/[user]/Documents/[projekt]/node_modules/.pnpm/vite@5.0.0_@types+node@20.9.1/node_modules/vite/dist/node/cli.js:764:24)       
>  ELIFECYCLE  Command failed with exit code 1.
> ```
> 
> if i comment out DynamicPublicDirectory it works fine
> 
> 
> #### Workaround:
> Currently Vite is only warning, so it can simply be ignored or you can globaly activate "module" and rename vite.config to `vite.config.cjs`.

I will come back in my next free time, thank you for reporting the issue!!

**Comment by Keavon** [comment]
This is failing for me entirely and I'm only on Vite `^4.4.5`:

> failed to load config from C:\Users\Keavon\Projects\Graphite\frontend\vite.config.ts
> error when starting dev server:
> TypeError: DynamicPublicDirectory is not a function
>     at file:///C:/Users/Keavon/Projects/Graphite/frontend/vite.config.ts.timestamp-1702169850413-459626d650237.mjs:38:5
> vite exited with code 1

My Vite config file is called `vite.config.ts` and I'm using the ESM import syntax: `import DynamicPublicDirectory from "vite-multiple-assets";`. And my `package.json` has `"type": "module",`. I did try renaming my config to `vite.config.cts` to no avail.

Seeking advice, thank you!

**Comment by nguyenbatranvan** [comment]
You can try again with version `1.2.6` that I just pushed!!!

**Comment by Keavon** [comment]
Thank you @nguyenbatranvan, that's working beautifully!

While I have your attention, I have one question: is there a way to put the files from one directory into a subdirectory of the output? So while the default `public` folder is where I put my favicon and stuff, the place where I'm putting my `external-assets` ends up as a sibling of the favicon when I'd rather it be contained in an `external-assets` directory that is, instead, the sibling of the favicon. I'd rather avoid double-wrapping my external assets in a `external-assets/external-assets` nested directory structure.

**Comment by nguyenbatranvan** [comment]
> Thank you @nguyenbatranvan, that's working beautifully!
> 
> While I have your attention, I have one question: is there a way to put the files from one directory into a subdirectory of the served output? So while the default Vite `public` folder is where I put my favicon and stuff, the place where I'm putting my `external-assets` (elsewhere in my monorepo, linked using your plugin) ends up served at the root with its contents as siblings of the favicon. But I'd rather it be contained in an `external-assets` subdirectory of the served output (so it'd be `localhost:8080/favicon.ico` and `localhost:8080/external-assets/asset1`). I'd rather avoid double-wrapping my external assets in a `external-assets/external-assets` nested directory structure in my monorepo.

I don't understand your question!!! Meaning you don't want to use vite's default directory (`public`)?

**Comment by Keavon** [comment]
Sorry, indeed it wasn't very clear. I'll try to rephrase with some examples:

I have a monorepo with this structure:
- external-assets/
    - asset-1.json
    - asset-2.json
- frontend/
    - src/
    - public/
        - favicon.ico
    - vite.config.ts

In `vite.config.ts` I have this:
```
plugins: [DynamicPublicDirectory(["../external-assets"])]
```

Per default, anything in the `public` directory (like `favicon.ico`) gets served at the root like `localhost:8080/favicon.ico`. This also means, thanks to your extension allowing me to have essentially multiple `public` directories, I'm currently able to also access `localhost:8080/asset-1.json` and `localhost:8080/asset-2.json`. However, I would prefer everything from the `external-assets` directory by served under the `/external-assets` subdirectory, like: `localhost:8080/external-assets/asset-1.json`.

One way that I'm not fond of is changing my monorepo directory structure like so:

- external-assets/
    - external-assets/
        - asset-1.json
        - asset-2.json
- frontend/
    - ...

I was wondering if you can suggest a way to get an additional public folder included with your extension to use its folder name as a subdirectory in the URL.

**Comment by nguyenbatranvan** [comment]
> Sorry, indeed it wasn't very clear. I'll try to rephrase with some examples:
> 
> I have a monorepo with this structure:
> 
> * external-assets/
>   
>   * asset-1.json
>   * asset-2.json
> * frontend/
>   
>   * src/
>   * public/
>     
>     * favicon.ico
>   * vite.config.ts
> 
> In `vite.config.ts` I have this:
> 
> ```
> plugins: [DynamicPublicDirectory(["../external-assets"])]
> ```
> 
> Per default, anything in the `public` directory (like `favicon.ico`) gets served at the root like `localhost:8080/favicon.ico`. This also means, thanks to your extension allowing me to have essentially multiple `public` directories, I'm currently able to also access `localhost:8080/asset-1.json` and `localhost:8080/asset-2.json`. However, I would prefer everything from the `external-assets` directory by served under the `/external-assets` subdirectory, like: `localhost:8080/external-assets/asset-1.json`.
> 
> One way that I'm not fond of is changing my monorepo directory structure like so:
> 
> * external-assets/
>   
>   * external-assets/
>     
>     * asset-1.json
>     * asset-2.json
> * frontend/
>   
>   * ...
> 
> I was wondering if you can suggest a way to get an additional public folder, that's included with your extension, to use its folder name as a subdirectory in the URL.

Nice!! I understand what you want!! You can create an issue and if you have time, I will update it as soon as possible

**Comment by Keavon** [comment]
Sure, I'll copy over my request into an issue. I think you can safely close this one now too, as it appears to be all working now with ES module syntax.

**Comment by nguyenbatranvan** [comment]
> Sure, I'll copy over my request into an issue. I think you can safely close this one now too, as it appears to be all working now with ES module syntax.

tks bro!!!
